services:
  - type: web
    name: textscope
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn src.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 5 --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: textscope-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENVIRONMENT
        value: "production"
      - key: PYTHONPATH
        value: "."
      - key: MAX_CONTENT_LENGTH
        value: "1000000"
      - key: REQUEST_TIMEOUT
        value: "60"
      - key: RATE_LIMIT_PER_MINUTE
        value: "30"
      - key: CORS_ORIGINS
        value: "*"
      - key: LOG_LEVEL
        value: "INFO"
      - key: WORKERS
        value: "2"
    healthCheckPath: /health
    autoDeploy: true
    numInstances:
      min: 1
      max: 2
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70
      targetCPUPercent: 70

databases:
  - name: textscope-db
    databaseName: textscope
    ipAllowList: []
    plan: starter 