services:
  - type: web
    name: textscope
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p nltk_data
      python -m textblob.download_corpora
      python -c "
      import nltk
      nltk.download('punkt', download_dir='nltk_data')
      nltk.download('averaged_perceptron_tagger', download_dir='nltk_data')
      nltk.download('maxent_ne_chunker', download_dir='nltk_data')
      nltk.download('words', download_dir='nltk_data')
      nltk.download('stopwords', download_dir='nltk_data')
      nltk.download('wordnet', download_dir='nltk_data')
      nltk.download('brown', download_dir='nltk_data')
      nltk.download('conll2000', download_dir='nltk_data')
      nltk.download('movie_reviews', download_dir='nltk_data')
      "
    startCommand: gunicorn src.main:app -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: textscope-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENVIRONMENT
        value: "production"
      - key: PYTHONPATH
        value: "."
      - key: NLTK_DATA
        value: "/opt/render/project/src/nltk_data"
    disk:
      name: nltk-data
      mountPath: /opt/render/project/src/nltk_data
      sizeGB: 1

databases:
  - name: textscope-db
    databaseName: textscope
    ipAllowList: [] 